import os
from dotenv import load_dotenv

load_dotenv()

MONGO_URI = os.getenv("MONGO_URI")
DB_NAME = os.getenv("DB_NAME")
TRANSACTIONS_COLLECTION = os.getenv("TRANSACTIONS_COLLECTION")
INVOICES_COLLECTION = os.getenv("INVOICES_COLLECTION")
RECONCILIATION_LOGS_COLLECTION = os.getenv("RECONCILIATION_LOGS_COLLECTION")
VECTOR_STORE_COLLECTION = os.getenv("VECTOR_STORE_COLLECTION")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")